# Generated by Django 5.0.6 on 2024-05-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutordb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
    ]
