# Generated by Django 5.0.6 on 2024-05-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutordb', '0004_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phonetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
    ]
